/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_leo_com_jnidemo_UninstallStatics */

#ifndef _Included_test_leo_com_jnidemo_UninstallStatics
#define _Included_test_leo_com_jnidemo_UninstallStatics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_leo_com_jnidemo_UninstallStatics
 * Method:    watchUninstallEvent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_leo_com_jnidemo_UninstallStatics_watchUninstallEvent
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
